name: Flutter Build and Release APP

on:
  push:
    branches:
      - main
    tags:
      - '*'  # Trigger on all tags

jobs:
  build_and_release:
    name: Build, Upload, and Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release  # Include --release for release mode

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-app
          path: build/app/outputs/apk/release/app-release.apk  # Update path if needed

      - name: Create GitHub Release (if tag)
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')  # Only on tag push
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Access token with release permissions
        with:
          tag_name: ${{ github.ref }}  # Use full ref to extract tag later
          artifacts: /tmp/app/app-release.apk  # Reference uploaded artifact
          # Extract tag name from full ref
          release_name: ${{ steps.extract_tag_name.outputs.tag_name }}
          body: "Automatic release for tag ${{ steps.extract_tag_name.outputs.tag_name }}"  # Optional release description

      - name: Extract Tag Name (helper step)
        id: extract_tag_name  # Define an id for output access
        run: |
          # Regex to extract tag name from full ref (adjust if needed)
          tag_name=$(echo "${{ github.ref }}" | sed 's/^refs\/tags\///')
          echo "::set-output name=tag_name::$tag_name"  # Set output variable